- name: "configure {{ component }}"
  become: yes
  # hosts: "{{ component }}"
  hosts: localhost  #this is for terraform-ansible connection
  connection: local
  roles: # this will automatically load a folder called roles in current working directory.
  - "{{ component }}"